config/routes.rb
Rails.application.routes.draw do

  root 'pets#index'

  resources :pets

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :person
  belongs_to :race
end

app/models/race.rb
class Race < ActiveRecord::Base
	has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
  	@pets = Pet.all
  end

  def show
  	@pet = Pet.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackPets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/index.html.erb
<h1>Listado de mascotas</h1>
<ul>
	<% @pets.each do |pet| %>
		<% if (pet.status > 0) %>
			<li>
				<h2><%= pet.nickname %></h2>
				<%= image_tag pet.image , style: "width:200px" %>
				<small><%= pet.race.name %></small>
				<p><%= pet.description %></p>
				<!-- <a href="/pets/show">Ver detalle</a> -->
				<%= link_to "Ver Detalle", pet_path(pet) %>
			</li>
		<% end %>
	<% end %>
</ul>

app/views/pets/show.html.erb
<h1>Pets#show</h1>
<div class="mascota">
	<h2><%= @pet.nickname %></h2>
	<%= image_tag @pet.image , style: "width:200px" %>
	<small><%= @pet.race.name %></small>
	<p><%= @pet.description %></p>
	<!-- <a href="/pets/show">Ver detalle</a> -->
	<%= link_to "Ver Detalle", pet_path(pet) %>
</div>